ALTER TABLE "novel_import_sources" ADD COLUMN "cover_source_url" text;--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD COLUMN "cover_key" text;--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD COLUMN "cover_status" varchar(16) DEFAULT 'missing' NOT NULL;--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD COLUMN "cover_error" text;--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD COLUMN "cover_updated_at" timestamp with time zone;--> statement-breakpoint
CREATE INDEX "novel_import_sources_cover_status_idx" ON "novel_import_sources" USING btree ("cover_status","updated_at" DESC NULLS LAST,"id");--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD CONSTRAINT "novel_import_sources_cover_url_https" CHECK ("novel_import_sources"."cover_source_url" is null or "novel_import_sources"."cover_source_url" ~ '^https://');--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD CONSTRAINT "novel_import_sources_cover_key_valid" CHECK ("novel_import_sources"."cover_key" is null or ("novel_import_sources"."cover_key" ~ '^covers/[0-9a-f-]+[.](jpg|png|webp|avif)$' and "novel_import_sources"."cover_key" !~ '[.].[/]'));--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD CONSTRAINT "novel_import_sources_cover_status_valid" CHECK ("novel_import_sources"."cover_status" in ('missing', 'pending', 'ready', 'error'));--> statement-breakpoint
ALTER TABLE "novel_import_sources" ADD CONSTRAINT "novel_import_sources_cover_state_valid" CHECK (("novel_import_sources"."cover_status" = 'missing' and "novel_import_sources"."cover_source_url" is null and "novel_import_sources"."cover_key" is null and "novel_import_sources"."cover_error" is null) or ("novel_import_sources"."cover_status" = 'pending' and "novel_import_sources"."cover_source_url" is not null and "novel_import_sources"."cover_error" is null) or ("novel_import_sources"."cover_status" = 'ready' and "novel_import_sources"."cover_source_url" is not null and "novel_import_sources"."cover_key" is not null and "novel_import_sources"."cover_error" is null) or ("novel_import_sources"."cover_status" = 'error' and "novel_import_sources"."cover_source_url" is not null and "novel_import_sources"."cover_error" is not null));